name: Tests

on:
  push:
    branches:
     - main
  pull_request_target:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
      
      - uses: DevExpress/testcafe-build-system/actions/build@main
      
     
  test:
    runs-on: ubuntu-latest
    needs: [build]
    environment: CI
    steps:
      - uses: DevExpress/testcafe-build-system/actions/prepare@main
      
      - uses: DevExpress/testcafe-build-system/actions/test-npm@main
        with:
          task: test
 
